# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# RTD yaml version to use in parsing this file
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# Optionally declare the Python requirements required to build your docs
python:
  # We need pip to install our doc deps, the settings below execute
  # `pip install .[doc]` in the rtd process.
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
  